export { EasyAuthService } from './core/easy-auth.service';

export { authConfig,
         api,
         id,
         query,
         secure,
         cacheable,
         key,
         IAuth,
         IConfig,
         EasyConnect,
         container,
         All,
         Add,
         Query,
         Update,
         Delete,
         AuthType,
         Get_All, 
         Get_Query,
         Get_Current,
         Current,
         Token,
         HttpFactory, 
         EasyTokenAuth, 
         EasyAuth,
         AuthFactory,
         Login,
         Logout,
         Register,
         Validate,
         ValidateData,
         EasyPrototype, 
         EasyFactory, 
         EasySingleton, Easy } from 'easy-connect';
         

